services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-latest
    restart: always

  discord_tool_bot:
    build: ./discord_tool_bot
    command: node .
    restart: always
    depends_on:
      - voicevox
    environment:
      DISCORD_BOT_TOKEN:
      clientId:
      guildId:
      ownerId:
      NOTIFY_CHANNEL:
      Reading_Channel:
      Reading_Role_Id:
      Voice_Channel_Id:
      If_Reding: true
      If_Notify_Status_Voice_Channel: true
      VOICEVOX_API_URL: http://voicevox:50021
      VOICEVOX_Speaker_Id: 3
      VOICEVOX_isAuth: false
      VOICEVOX_API_TOKEN:
