services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-latest
    restart: always

  discord_tool_bot:
    build: ./discord_tool_bot
    command: node .
    restart: always
    depends_on:
      - voicevox
    volumes:
      - ./discord_tool_bot/settings.json:/app/settings.json
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      clientId: ${clientId}
      guildId: ${guildId}
      ownerId: ${ownerId}
      VOICEVOX_API_URL: ${VOICEVOX_API_URL}
      VOICEVOX_Speaker_Id: ${VOICEVOX_Speaker_Id}
      VOICEVOX_isAuth: ${VOICEVOX_isAuth}
      VOICEVOX_API_TOKEN: ${VOICEVOX_API_TOKEN}
      MAX_TEXT_LENGTH: 50
      Language: ja-JP
